algoritmo "Exercício 4"

var
   lado1, lado2, lado3, perimetro: real

inicio

   //Dado os três lados de um triângulo determinar o perímetro do mesmo.
   escreval("Digite o tamanho do lado 1 do triângulo: ")
   leia(lado1)

   escreval("Digite o tamanho do lado 2 do triângulo: ")
   leia(lado2)

   escreval("Digite o tamanho do lado 3 do triângulo: ")
   leia(lado3)

   perimetro <- lado1 + lado2 + lado3

   escreval("O perímetro do triângulo é: ", perimetro)

fimalgoritmo