Algoritmo "exercicio21"
// Lê um número e exibe se ele é positivo ou negativo

Var
   // Seção de Declarações das variáveis
   N: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("Digite um número: ")
   leia (N)
   se (N > 0) entao
      escreval ("O número é positivo!")
   senao
      se (N < 0) entao
         escreval ("O número é negativo!")
      fimse
   fimse

Fimalgoritmo